---
- hosts: all || localhost
  vars:
  - oah_command: install
  - HOME: /home/vagrant

  vars_files:
    - ../oah-config.yml

  pre_tasks:
#     - import_tasks: tasks/bes_env_config.yml
    - name: "printing debug msg"
      become: yes
      debug:
        msg: In pre_tasks
    # Will need the shell provision to install python-minimal first
    - name: Install python for Ansible
      become: yes
      raw: test -e /usr/bin/python || (sudo apt -y update && apt install -y python-minimal)
    - include: tasks/init-debian.yml
      when: ansible_os_family == 'Debian'
  roles:
    # Essential roles.
      - { role: oah.threatdragon, when: BESMAN_ENV == 'lf-java-RT' }
#     - oah.bes
#     - oah.desktop
      #- oah.vscode


    # Conditionally-installed roles.

    # Roles for security and stability on production.
